traitlets/traitlets.py

- Now, one can only link one source to one target.
- Even if the initial assignment fails (for example because of a custom validation TraitError), the `on_trait_change` callbacks are still registered.

Allow only one target in link and directional_link

---

traitlets/config/application.py

Actually #24 is broken in some cases. 
:-(

log can be Nonetype

---

docs/source/using_traitlets.rst
traitlets/tests/test_traitlets.py
traitlets/traitlets.py

As per discussion with @takluyver .

has_trait function

---

traitlets/tests/test_traitlets.py
traitlets/traitlets.py

Instead of None
Prerequisite for fixing jupyter/nbconvert#41

Use NoDefaultSpecified as sentinel for Type default

---

MANIFEST.in

add missing markdown files to MANIFEST.in

---

traitlets/config/configurable.py
traitlets/config/tests/test_application.py

fix config file generation

---

traitlets/traitlets.py

The solution proposed by @sccolbert to the problem with unbound method in the observe decorator. @rmorshea.

Making a bound method in the @observe decorator

---

traitlets/utils/importstring.py
traitlets/utils/tests/test_importstring.py

Finish up #58
closes #57, closes #58

Cast unicode module name to str on Python 2

---

traitlets/traitlets.py

Abstract `get` from `__get__` similarly to `set` and `__set__`
Example involving an "on get" notifier using `@retrieve` like `@observe`:
```python
def retrieve(name):
return RetrieveHandler(name)
class RetrieveHandler(EventHandler):
def __init__(self, name):
self._name = name
def instance_init(self, inst):
if not hasattr(inst, '_retrieve_handlers'):
inst._retrieve_handlers = {}
if self._name in inst._retrieve_handlers:
raise TraitError("A retriever for the trait '%s' has "
"already been registered" % self._name)
method = types.MethodType(self.func, inst)
inst._retrieve_handlers[self._name] = method
class OnGetMixin(object):
def __get__(self, obj, cls=None):
if obj is None:
return self
value = super(OnGetMixin,self).get(obj, cls)
if self.name in obj._retrieve_handlers:
method = …
```

Modularize TraitType Get

---

traitlets/traitlets.py

- The `@validate` and `@observe` decorators docstrings were missing the documentation of the signature of the change and validation handlers.
- I added an important note in the docstring of the `@validate` decorator, which is a recommendation for authors of cross validator functions.
Let me explain in more details here.
- the owner is passed to the cross validator function, because we want the validation / coercion of the proposed value to be able to read other attributes of the owner, for example, to enforce min <= value <= max in a slider (flooring and capping proposed value with `min` and `max`). 
- as a consequence, the author of such cross validator could also potentially make changes to other attributes (pushing `min` and `max` around when changing the value).
The note is there to …

@observe and @validate docstrings

---

traitlets/tests/test_traitlets.py
traitlets/traitlets.py

Adding transform attribute to directional link

---

traitlets/traitlets.py

... rather than in `instance_init`.

Call contained trait types' `class_init` and set `this_class` in `class_init`

---

README.md

no pre in pip install -e

---

traitlets/traitlets.py

These changes follow from those relating to `this_class` in #129.

stop setting `this_class`

---

traitlets/traitlets.py

reduces the number of iterations being performed in `Hastraits.class_traits` and `Hastraits.traits`

faster trait collection via metadata

---

traitlets/traitlets.py

just adds a few docstrings and edits ones associated with validation handlers.

various docstring fixes

---

docs/source/migration.rst

@SylvainCorlay this is the last thing I see for 4.1.

document `@observe_compat` in migration

---

docs/source/changelog.rst
docs/source/config.rst
docs/source/migration.rst
docs/source/using_traitlets.rst
traitlets/traitlets.py

- use 4.1 API in config example
- various minor formatting/typo fixes
@SylvainCorlay @rmorshea after merging this one, I'll cut 4.1.

Minor fixes/typos after a pass through the docs

---

traitlets/traitlets.py

Use a standard contextmanager for setting it everywhere (except
hold_trait_notifications, which is complex enough that I'm nervous about
refactoring it here without more input.).
Set _cross_validation_lock in TraitType.setup_instance, which is called
before __init__. Previously it was being implicitly initialized in
different places.

MAINT: Systematize access to TraitType._cross_validation_lock.

---

traitlets/config/loader.py
traitlets/config/tests/test_loader.py

in JSON loader context manager

avoid deleting config on failed json dumps

---

traitlets/config/configurable.py
traitlets/config/tests/test_configurable.py

and use regular warnings when there is no logger

log ignored config if no near matches

---

traitlets/config/application.py
traitlets/config/tests/test_application.py

Some applications (most?) should halt on failing to load config, this lets them choose by setting `raise_config_file_errors = True`.

Allow Applications to pick if they should allow config-file failure

---

traitlets/config/tests/test_application.py
traitlets/tests/utils.py

fixes untested typos in tests/utils

exercise help-output tests

---

traitlets/tests/test_traitlets.py
traitlets/traitlets.py

streamline `Dict.validate_elements` heuristic and closes #191

streamline validate elements with bug fix

---

docs/source/migration.rst

fix some typos

---

traitlets/config/configurable.py

closes #212 - import from future in config/configurable.py needs to add absolute_import

absolute_import in configurable

---

docs/source/migration.rst
traitlets/traitlets.py

Clarify details of `@observe` argument docs

---

traitlets/config/application.py
traitlets/config/configurable.py
traitlets/traitlets.py
traitlets/utils/bunch.py
traitlets/utils/tests/test_bunch.py

it's still a dict, so everything should be 100% backward-compatible.
include yet-another implementation of bunch in utils.bunch
closes #217

add attr-access to change dicts

---

traitlets/traitlets.py

Reverts deprecations in ipython/traitlets#209
closes #231

undeprecate `class_traits` and `class_trait_names`

---

traitlets/utils/bunch.py
traitlets/utils/tests/test_bunch.py

so they are exposed to attribute completions

add keys to bunch.__dir__

---

traitlets/config/tests/test_configurable.py
traitlets/tests/test_traitlets.py
traitlets/traitlets.py

add traitlets version to deprecation warnings

---

setup.py

add missing mock dependency for py2 tests

---

traitlets/config/application.py

See also:
https://docs.python.org/2/library/sys.html#sys.executable
Also, cleanup some unneeded whitespace.

Test for sys.executable before trying to use it since it can be None.

---

traitlets/traitlets.py

Remove init

---

traitlets/traitlets.py

- default value for `allow_none` is now `False` instead of `None`.
- fix what appears to be a typo in maybe_constructor_keywords.

allow_none is boolean

---

traitlets/config/application.py
traitlets/config/tests/test_application.py

and include absolute path in the warning to clarify where the collision happened.
avoids collision warning when path priority causes override, which is normal and shouldn't result in a warning.
Previously, the warning could be triggered when `/etc/jupyter/some_config.py` and `~/.jupyter/some_config.py` 
closes #279

ensure .py/.json collision detection only affects pairs in the same directory

---

docs/source/changelog.rst

I'll cut 4.3.0b1 once this is merged.
cc @SylvainCorlay @Carreau @rmorshea

Changes for 4.3

---

traitlets/traitlets.py

Edit docstring for Dict.__init__()

---

docs/source/utils.rst

Document link and directional_link

---

traitlets/config/application.py

instead of:
looking for config in None
output:
looking for config in /path/to/cwd

Improve "looking for config" message when no path specified

---

.travis.yml
traitlets/traitlets.py

Test Python 3.6

---

traitlets/config/application.py

could affect parent classes incorrectly.

avoid modifying inherited class attr

---

docs/source/changelog.rst

Mainly for Python 3.6 workaround.
I'll release once this is merged.

changes for 4.3.1

---

traitlets/config/loader.py
traitlets/config/tests/test_loader.py

include contents of the config value

nicer repr of LazyConfigValues

---

traitlets/traitlets.py

None is one of anything, after all.
related to #342

Any should allow None by default

---

traitlets/traitlets.py

with examples
this can wait for #306. I'll rebase after that since it's touching the same code, and that one changes the statements made here about keys.
cf #294

further clarify Dict docstring

---

docs/source/changelog.rst

Tiny release, removing a couple of deprecations to make upgrading existing packages more pleasant.
cc @JamiesHQ

Changelog for 4.3.2

---

traitlets/tests/test_traitlets.py
traitlets/traitlets.py

The new ``link`` method simply reinstates the link.

Add link method to link and dlink

---

traitlets/config/application.py

Tell about help-all last.

---

traitlets/traitlets.py

Error message got messed up after https://github.com/ipython/traitlets/pull/402. This fixes is.

fix instance error message

---

docs/source/config.rst

remove incorrect version arg from json config doc

---

traitlets/config/application.py

+ Undetect due to missing TC and no code using it.

fix(help): minor typo in print_examples()

---

.travis.yml

this should help prevent regressions in real-world cases that might not be covered by the traitlets tests
cf #472

test some downstream projects

---

traitlets/utils/descriptions.py

remove one useless return line

---

traitlets/config/configurable.py
traitlets/config/tests/test_configurable.py

Use log from parent in LoggingConfigurable.

---

traitlets/traitlets.py

Make this a bulleted list in sphinx, as intended.

Fix formatting.

---

docs/source/utils.rst
setup.py
traitlets/__init__.py
traitlets/utils/decorators.py
traitlets/utils/tests/test_decorators.py

Add trait-names autocompletion support

---

docs/source/trait_types.rst
traitlets/tests/test_traitlets.py
traitlets/traitlets.py

https://github.com/ipython/traitlets/issues/554

cherrypick #333 and #523 onto 4.3.x

---

.travis.yml

Travis CI: Fix Travis build configuration validation issues

---

.travis.yml

traittypes have been failing for a long time stop testing on it for now.

Stop testing traittypes which fails.

---

docs/source/changelog.rst

Most of these should not have impact on API.

Review and document a couple more 5.0 PRs.

---

traitlets/config/application.py
traitlets/config/configurable.py
traitlets/config/loader.py
traitlets/config/sphinxdoc.py
traitlets/tests/_warnings.py
traitlets/traitlets.py
traitlets/utils/descriptions.py
traitlets/utils/importstring.py

Use my in-progess project (vélin, https://carreau/minirst).

DOC: Autoreformat all docstring to by numpydoc compliant.

---

docs/source/changelog.rst

A very sad story of lines that got separated.

Reunite lines

---

docs/source/config.rst

`does one things` --> `does one thing`

correct typo

---

setup.py

Update metadata in setup.py

---

setup.py

See https://github.com/ipython/ipython/issues/12498

More checks in setup.py for wrong version.

---

traitlets/config/tests/test_application.py
traitlets/tests/test_traitlets.py
traitlets/traitlets.py

allow_none wasn't taken into account in `from_string`, meaning `--alias=None` didn't work as intended.
closes #612

handle allow_none in from_string

---

traitlets/config/loader.py
traitlets/config/tests/test_application.py

Original error is displayed. Now looks like:
```
Error loading argument App.opt=['1', '2'], opt only accepts one value, got 2: ['1', '2']
```
related to #614 
Leaving #614 open to the possibility of changing the behavior of multiply defined scalar options to accept the last one, which was the de facto behavior of traitlets 4.

nicer error message for multiply defined config

---

docs/source/changelog.rst
traitlets/tests/test_traitlets.py
traitlets/traitlets.py

handle default_value=None in Container traits

---

traitlets/tests/test_traitlets_enum.py

Closes https://github.com/ipython/traitlets/issues/661.

Fix string assertion for python3.10

---

traitlets/config/tests/test_loader.py
traitlets/traitlets.py

Fixes #668 ( passing a single element for a list on CLI)

---

.github/workflows/tests.yml

test on 3.10

---

.github/workflows/release.yml

as we do most places these days
token added to repo secrets

publish releases from GHA

---

examples/myapp.py

Pointed out in a reddit discussion

DOC: Add log example

---

docs/source/utils.rst

This is a redo of [a former pull request](https://github.com/ipython/traitlets/pull/697/commits/a69ff614818290c8d543e98b5d1df28ce5051083) that created a merge conflict that could not be fixed because they were on my master branch.
If I'm doing PRs incorrectly, I'm open to information about a better approach.

Put description of `signature_has_traits` after the header for it.

---

.pre-commit-config.yaml
MANIFEST.in
docs/source/conf.py
examples/myapp.py
pyproject.toml
setup.py
traitlets/__init__.py
traitlets/config/application.py
traitlets/config/loader.py
traitlets/traitlets.py
traitlets/utils/bunch.py
traitlets/utils/descriptions.py
traitlets/utils/text.py

- Adds minimal typing support with semi-strict config so that downstream projects can use traitlets typings.

Add mypy support

---

examples/myapp.py

Fix typing errors

---

traitlets/tests/test_traitlets.py
traitlets/traitlets.py

Make __all__ explicit and validate in test

---

traitlets/config/application.py
traitlets/config/tests/test_application.py

Fix KeyError in Application.get_default_logging_config

---

docs/source/changelog.rst

Add changelog for 5.4

---

traitlets/config/application.py
traitlets/traitlets.py
traitlets/utils/decorators.py

Adds typings to several helper functions

Add more typings

---

pyproject.toml

Add project description

---

traitlets/traitlets.py

improves inspection via tools like sphinx autodoc
related discussion: https://github.com/jupyterhub/autodoc-traits/issues/30

define trait.__doc__ = trait.help

---

docs/source/config-api.rst

Add a couple more classes used downstream.

Add more api docs

---

traitlets/config/application.py

I needed to fix this project, not “ipython”, so I re-created the PR.
ipython/ipython#14902
Thanks.

The --config option with absolute paths will be loaded only once.
